// <auto-generated />
using System;
using ContaCorrente.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContaCorrente.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ContaCorrenteDbContext))]
    [Migration("20260828012819_AdicionaFormaPagamento")]
    partial class AdicionaFormaPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ContaCorrente.Api.Domain.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("Saldo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("ContaCorrente.Api.Domain.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OcorridaEm")
                        .HasColumnType("TEXT");

                    b.Property<long>("SaldoResultante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "FormaPagamento");

                    b.HasIndex("ContaId", "OcorridaEm");

                    b.ToTable("Movimentacoes", (string)null);
                });

            modelBuilder.Entity("ContaCorrente.Api.Domain.Movimentacao", b =>
                {
                    b.HasOne("ContaCorrente.Api.Domain.Conta", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContaCorrente.Api.Domain.Conta", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
